INSERT INTO Professor (idProfessor, Nome, Instituto) VALUES
-- Professores do Instituto de Computação (IC)
    (0, 'Dummy', 'IC'),
    (1, 'Alexandre Xavier Falcão', 'IC'),
    (2, 'Allan Mariano de Souza', 'IC'),
    (3, 'Anderson de Rezende Rocha', 'IC'),
    (4, 'André Santanchè', 'IC'),
    (5, 'Breno Bernard Nicolau de França', 'IC'),
    (6, 'Bruno Barbieri de Pontes Cafeo', 'IC'),
    (7, 'Carlos Alberto Astudillo Trujillo', 'IC'),
    (8, 'Cecília Mary Fischer Rubira', 'IC'),
    (9, 'Christiane Neme Campos', 'IC'),
    (10, 'Claudia Maria Bauzer Medeiros', 'IC'),
    (11, 'Edmundo Roberto Mauro Madeira', 'IC'),
    (12, 'Edson Borin', 'IC'),
    (13, 'Emanuel Felipe Duarte', 'IC'),
    (14, 'Esther Luna Colombini', 'IC'),
    (15, 'Fábio Luiz Usberti', 'IC'),
    (16, 'Flávio Keidi Miyazawa', 'IC'),
    (17, 'Guido Costa Souza de Araújo', 'IC'),
    (18, 'Guilherme P. Telles', 'IC'),
    (19, 'Hélio Pedrini', 'IC'),
    (20, 'Hervé Cédric Yviquel', 'IC'),
    (21, 'Hilder Vitor Lima Pereira', 'IC'),
    (22, 'Islene Calciolari Garcia', 'IC'),
    (23, 'Jacques Wainer', 'IC'),
    (24, 'João Meidanis', 'IC'),
    (25, 'Jorge Stolfi', 'IC'),
    (26, 'Juliana Freitag Borin', 'IC'),
    (27, 'Julio Cesar dos Reis', 'IC'),
    (28, 'Julio César López Hernández', 'IC'),
    (29, 'Leandro Aparecido Villas', 'IC'),
    (30, 'Lehilton Lelis Chaves Pedrosa', 'IC'),
    (31, 'Lucas Francisco Wanner', 'IC'),
    (32, 'Luiz Fernando Bittencourt', 'IC'),
    (33, 'Marcelo da Silva Reis', 'IC'),
    (34, 'Marcos Medeiros Raimundo', 'IC'),
    (35, 'Nelson Luis Saldanha da Fonseca', 'IC'),
    (36, 'Orlando Lee', 'IC'),
    (37, 'Paulo César Centoducatte', 'IC'),
    (38, 'Paulo Lício de Geus', 'IC'),
    (39, 'Pedro Jussieu de Rezende', 'IC'),
    (40, 'Rafael Crivellari Saliba Schouery', 'IC'),
    (41, 'Ricardo Dahab', 'IC'),
    (42, 'Ricardo Pannain', 'IC'),
    (43, 'Rodolfo Jardim de Azevedo', 'IC'),
    (44, 'Ruben Interian', 'IC'),
    (45, 'Sandra Eliza Fontes de Avila', 'IC'),
    (46, 'Sandro Rigo', 'IC'),
    (47, 'Santiago Valdés Ravelo', 'IC'),
    (48, 'Zanoni Dias', 'IC');

-- Professores do Instituto de Física Gleb Wataghin (IFGW)
INSERT INTO Professor (idProfessor, Nome, Instituto) VALUES
    (49, 'Prof. Dr. Abner de Siervo', 'IFGW'),
    (50, 'Profa. Dra. Alessandra Tomal', 'IFGW'),
    (51, 'Prof. Dr. Alex Antonelli', 'IFGW'),
    (52, 'Prof. Dr. Alexandre Fontes da Fonseca', 'IFGW'),
    (53, 'Prof. Dr. Amir Ordacgi Caldeira', 'IFGW'),
    (54, 'Prof. Dr. Anderson Campos Fauth', 'IFGW'),
    (55, 'Prof. Dr. André Alexandre de Thomaz', 'IFGW'),
    (56, 'Prof. Dr. André Koch Torres de Assis', 'IFGW'),
    (57, 'Prof. Dr. Andre Monteiro Paschoal', 'IFGW'),
    (58, 'Prof. Dr. Antonio Riul Junior', 'IFGW'),
    (59, 'Prof. Dr. Antonio Vidiella Barranco', 'IFGW'),
    (60, 'Profa. Dra. Arlene Cristina Aguilar', 'IFGW'),
    (61, 'Prof. Dr. Arnaldo Naves de Brito', 'IFGW'),
    (62, 'Profa. Dra. Carola Dobrigkeit Chinellato', 'IFGW'),
    (63, 'Prof. Dr. Christoph Friedrich Deneke', 'IFGW'),
    (64, 'Profa. Dra. Cris Adriano', 'IFGW'),
    (65, 'Profa. Dra. Cristiane Jahnke Fiorini da Silva', 'IFGW'),
    (66, 'Prof. Dr. Cristiano Monteiro de Barros Cordeiro', 'IFGW'),
    (67, 'Prof. Dr. Daniel Mario Ugarte', 'IFGW'),
    (68, 'Prof. Dr. David Mendez Soares', 'IFGW'),
    (69, 'Prof. Dr. Diego Muraca', 'IFGW'),
    (70, 'Prof. Dr. Donato Giorgio Torrieri', 'IFGW'),
    (71, 'Prof. Dr. Douglas Soares Galvão', 'IFGW'),
    (72, 'Prof. Dr. Edison Zacarias da Silva', 'IFGW'),
    (73, 'Prof. Dr. Eduardo Granado Monteiro da Silva', 'IFGW'),
    (74, 'Prof. Dr. Eduardo Miranda', 'IFGW'),
    (75, 'Prof. Dr. Ernesto Kemp', 'IFGW'),
    (76, 'Prof. Dr. Ettore Segreto', 'IFGW'),
    (77, 'Profa. Dra. Fanny Béron', 'IFGW'),
    (78, 'Prof. Dr. Felippe Alexandre Silva Barbosa', 'IFGW'),
    (79, 'Profa. Dra. Flavia Sobreira', 'IFGW'),
    (80, 'Prof. Dr. Flávio Caldas da Cruz', 'IFGW'),
    (81, 'Prof. Dr. Francisco das Chagas Marques', 'IFGW'),
    (82, 'Prof. Dr. Francisco Paulo Marques Rouxinol', 'IFGW'),
    (83, 'Profa. Dra. Gabriela Castellano', 'IFGW'),
    (84, 'Prof. Dr. Guilherme Stecca Marcom', 'IFGW'),
    (85, 'Prof. Dr. Gustavo Silva Wiederhecker', 'IFGW'),
    (86, 'Prof. Dr. Iakov Veniaminovitch Kopelevitch', 'IFGW'),
    (87, 'Prof. Dr. Jonathas de Paula Siqueira', 'IFGW'),
    (88, 'Prof. Dr. José Antônio Brum', 'IFGW'),
    (89, 'Prof. Dr. José Augusto Chinellato', 'IFGW'),
    (90, 'Prof. Dr. Jun Takahashi', 'IFGW'),
    (91, 'Prof. Dr. Kleber Roberto Pirota', 'IFGW'),
    (92, 'Prof. Dr. Lázaro Aurélio Padilha Junior', 'IFGW'),
    (93, 'Prof. Dr. Leandro Russovski Tessler', 'IFGW'),
    (94, 'Prof. Dr. Luís Eduardo Evangelista de Araujo', 'IFGW'),
    (95, 'Prof. Dr. Luiz Fernando Zagonel', 'IFGW'),
    (96, 'Prof. Dr. Luiz Filipe Campos Faria', 'IFGW'),
    (97, 'Prof. Dr. Marcelo Knobel', 'IFGW'),
    (98, 'Prof. Dr. Marcos Cesar de Oliveira', 'IFGW'),
    (99, 'Prof. Dr. Marcus Aloizio Martinez de Aguiar', 'IFGW'),
    (100, 'Prof. Dr. Marcus Vinicius Segantini Bonança', 'IFGW'),
    (101, 'Prof. Dr. Mario Antonio Bernal Rodriguez', 'IFGW'),
    (102, 'Prof. Dr. Mário Noboru Tamashiro', 'IFGW'),
    (103, 'Prof. Dr. Maurice de Koning', 'IFGW'),
    (104, 'Prof. Dr. Maurício Urban Kleinke', 'IFGW'),
    (105, 'Profa. Dra. Mônica Alonso Cotta', 'IFGW'),
    (106, 'Prof. Dr. Newton Cesario Frateschi', 'IFGW'),
    (107, 'Prof. Dr. Odilon Divino Damasceno Couto Junior', 'IFGW'),
    (108, 'Prof. Dr. Orlando Luis Goulart Peres', 'IFGW'),
    (109, 'Prof. Dr. Pascoal José Giglio Pagliuso', 'IFGW'),
    (110, 'Profa. Dra. Patricia Camargo Magalhaes', 'IFGW'),
    (111, 'Prof. Dr. Pedro Cunha de Holanda', 'IFGW'),
    (112, 'Prof. Dr. Pierre Louis de Assis', 'IFGW'),
    (113, 'Prof. Dr. Rafael Luiz da Silva Rabelo', 'IFGW'),
    (114, 'Prof. Dr. Ricardo Antonio Mosna', 'IFGW'),
    (115, 'Prof. Dr. Ricardo Luís Doretto', 'IFGW'),
    (116, 'Prof. Dr. Ricardo Rodrigues Urbano', 'IFGW'),
    (117, 'Prof. Dr. Rickson Coelho Mesquita', 'IFGW'),
    (118, 'Prof. Dr. Sandro Guedes de Oliveira', 'IFGW'),
    (119, 'Prof. Dr. Silvio Antonio Sachetto Vitiello', 'IFGW'),
    (120, 'Prof. Dr. Thiago Pedro Mayer Alegre', 'IFGW'),
    (121, 'Prof. Dr. Thiago Vasconcelos Ribeiro', 'IFGW'),
    (122, 'Prof. Dr. Varlei Rodrigues', 'IFGW'),
    (123, 'Prof. Dr. Willian Massashi Hisano Natori', 'IFGW');

-- Professores do Instituto de Matemática, Estatística e Computação Científica (IMECC)
INSERT INTO Professor (idProfessor, Nome, Instituto) VALUES
    (124, 'Ademir Pastor Ferreira', 'IMECC'),
    (125, 'Adriano A. Moura', 'IMECC'),
    (126, 'Alessio Fiscella', 'IMECC'),
    (127, 'Anne Caroline Bronzi', 'IMECC'),
    (128, 'Argenis Jose Mendez Garcia', 'IMECC'),
    (129, 'Artem Lopatin', 'IMECC'),
    (130, 'Bianca M. R. Calsavara', 'IMECC'),
    (131, 'Christian H. Olivera', 'IMECC'),
    (132, 'Claudemir Fideles Bezerra Jr.', 'IMECC'),
    (133, 'Dessislava Kochloukova', 'IMECC'),
    (134, 'Diego S. Ledesma', 'IMECC'),
    (135, 'Douglas D. Novaes', 'IMECC'),
    (136, 'Eder de Moraes Correa', 'IMECC'),
    (137, 'Eduardo Garibaldi', 'IMECC'),
    (138, 'Ethan Guy Cotterill', 'IMECC'),
    (139, 'Gabriel Ponce', 'IMECC'),
    (140, 'Gabriela V. Planas', 'IMECC'),
    (141, 'Giuliano Angelo Zugliani', 'IMECC'),
    (142, 'Henrique N. Sá Earp', 'IMECC'),
    (143, 'Joachim Weber', 'IMECC'),
    (144, 'João Vitor da Silva', 'IMECC'),
    (145, 'Johnny Albert dos Santos Lima', 'IMECC'),
    (146, 'José Regis Azevedo Varão Filho', 'IMECC'),
    (147, 'Juan Francisco Camasca Fernández', 'IMECC'),
    (148, 'Ketty A. Rezende', 'IMECC'),
    (149, 'Laura Rifo', 'IMECC'),
    (150, 'Lino A. S. Grama', 'IMECC'),
    (151, 'Lucas C. F. Ferreira', 'IMECC'),
    (152, 'Mahendra P. Panthee', 'IMECC'),
    (153, 'Marcelo Firer', 'IMECC'),
    (154, 'Marcelo S. Montenegro', 'IMECC'),
    (155, 'Márcio Antonio de Faria Rosa', 'IMECC'),
    (156, 'Marcos B. Jardim', 'IMECC'),
    (157, 'Paulo R. C. Ruffino', 'IMECC'),
    (158, 'Pedro J. Catuogno', 'IMECC'),
    (159, 'Pietro Speziali', 'IMECC'),
    (160, 'Plamen E. Kochloukov', 'IMECC'),
    (161, 'Ricardo Miranda Martins', 'IMECC'),
    (162, 'Saeed Tafazolian', 'IMECC'),
    (163, 'Sahibzada Waleed Noor', 'IMECC'),
    (164, 'Sérgio A. Tozoni', 'IMECC'),
    (165, 'Tiago Jardim da Fonseca', 'IMECC'),
    (166, 'Viviana Jorgelina Del Barco', 'IMECC'),
    (167, 'Alex Rodrigo dos Santos Sousa', 'IMECC'),
    (168, 'Aluísio S. Pinheiro', 'IMECC'),
    (169, 'Benilton de Sá Carvalho', 'IMECC'),
    (170, 'Caio L. N. Azevedo', 'IMECC'),
    (171, 'Carlos Cesar Trucios Maza', 'IMECC'),
    (172, 'Christophe F. Gallesco', 'IMECC'),
    (173, 'Diego F. Bernardini', 'IMECC'),
    (174, 'Élcio Lebensztayn', 'IMECC'),
    (175, 'Filidor E. Labra', 'IMECC'),
    (176, 'Guilherme V. Nunes Ludwig', 'IMECC'),
    (177, 'Hildete P. Pinheiro', 'IMECC'),
    (178, 'Jesús Enrique Garcia', 'IMECC'),
    (179, 'Larissa A. Matos', 'IMECC'),
    (180, 'Mariana R. Motta', 'IMECC'),
    (181, 'Mauricio E. Zevallos Herencia', 'IMECC'),
    (182, 'Nancy L. Garcia', 'IMECC'),
    (183, 'Rafael P. Maia', 'IMECC'),
    (184, 'Ronaldo Dias', 'IMECC'),
    (185, 'Samara F. Kiihl', 'IMECC'),
    (186, 'Tatiana Benaglia', 'IMECC'),
    (187, 'Verónica A. González-Lopez', 'IMECC'),
    (188, 'Victor Freguglia Souza', 'IMECC');

-- Professores da Faculdade de Engenharia Elétrica e de Computação (FEEC)
INSERT INTO Professor (idProfessor, Nome, Instituto) VALUES
    -- DCA – Departamento de Engenharia de Computação e Automação
    (189, 'Alim Pedro de Castro Goncalves', 'FEEC'),
    (190, 'Christian Rodolfo Esteve Rothenberg', 'FEEC'),
    (191, 'Denis Gustavo Fantinato', 'FEEC'),
    (192, 'Eduardo Alves do Valle Junior', 'FEEC'),
    (193, 'Eric Rohmer', 'FEEC'),
    (194, 'Fernando Antonio Campos Gomide', 'FEEC'),
    (195, 'Fernando José Von Zuben', 'FEEC'),
    (196, 'Jose Mario de Martino', 'FEEC'),
    (197, 'José Raimundo de Oliveira', 'FEEC'),
    (198, 'Letícia Rittner', 'FEEC'),
    (199, 'Levy Boccato', 'FEEC'),
    (200, 'Marco Aurélio Amaral Henriques', 'FEEC'),
    (201, 'Matheus Souza', 'FEEC'),
    (202, 'Paula Dornhofer Paro Costa', 'FEEC'),
    (203, 'Rafael Ferrari', 'FEEC'),
    (204, 'Ricardo Ribeiro Gudwin', 'FEEC'),
    (205, 'Roberto de Alencar Lotufo', 'FEEC'),
    (206, 'Romis Ribeiro de Faissol Attux', 'FEEC'),
    (207, 'Wu Shin Ting', 'FEEC'),
    
    -- DECOM – Departamento de Comunicações
    (208, 'Aldario Chrestani Bordonalli', 'FEEC'),
    (209, 'Bruno Sanches Masiero', 'FEEC'),
    (210, 'Dalton Soares Arantes', 'FEEC'),
    (211, 'Darli Augusto de Arruda Mello', 'FEEC'),
    (212, 'Edgar Eduardo Benitez Olivo', 'FEEC'),
    (213, 'Evandro Conforti', 'FEEC'),
    (214, 'Gilliard Nardel Malheiros Silveira', 'FEEC'),
    (215, 'Gustavo Fraidenraich', 'FEEC'),
    (216, 'Hélio Waldman', 'FEEC'),
    (217, 'Hugo Enrique Hernandez Figueroa', 'FEEC'),
    (218, 'João Marcos Travassos Romano', 'FEEC'),
    (219, 'José Candido Silveira Santos Filho', 'FEEC'),
    (220, 'Leonardo de Souza Mendes', 'FEEC'),
    (221, 'Luís Geraldo Pedroso Meloni', 'FEEC'),
    (222, 'Luiz César Martini', 'FEEC'),
    (223, 'Max Henrique Machado Costa', 'FEEC'),
    (224, 'Michel Daoud Yacoub', 'FEEC'),
    (225, 'Michel Zamboni Rached', 'FEEC'),
    (226, 'Paulo Cardieri', 'FEEC'),
    (227, 'Reginaldo Palazzo Jr.', 'FEEC'),
    (228, 'Renato da Rocha Lopes', 'FEEC'),
    (229, 'Yuzo Iano', 'FEEC'),
    
    -- DEEB – Departamento de Eletrônica e Engenharia Biomédica
    (230, 'Antônio Augusto Fasolo Quevedo', 'FEEC'),
    (231, 'Carina Marconi Germer', 'FEEC'),
    (232, 'Cesar José Bonjuani Pagan', 'FEEC'),
    (233, 'Eduardo Tavares Costa', 'FEEC'),
    (234, 'Fabiano Fruett', 'FEEC'),
    (235, 'Gilmar Barreto', 'FEEC'),
    (236, 'Hudson Giovani Zanin', 'FEEC'),
    (237, 'José Alexandre Diniz', 'FEEC'),
    (238, 'Jose Claudio Geromel', 'FEEC'),
    (239, 'Jose Wilson Magalhaes Bassani', 'FEEC'),
    (240, 'Leandro Tiago Manera', 'FEEC'),
    (241, 'Leonardo Abdala Elias', 'FEEC'),
    (242, 'Marco Roberto Cavallari', 'FEEC'),
    (243, 'Marcos Vinícius Puydinger dos Santos', 'FEEC'),
    (244, 'Mateus Giesbrecht', 'FEEC'),
    (245, 'Pedro Xavier de Oliveira', 'FEEC'),
    
    -- DSE – Departamento de Sistemas e Energia
    (246, 'Akebo Yamakami', 'FEEC'),
    (247, 'Carlos Alberto de Castro Junior', 'FEEC'),
    (248, 'Cecília de Freitas Morais', 'FEEC'),
    (249, 'Christiano Lyra Filho', 'FEEC'),
    (250, 'Daniel Dotta', 'FEEC'),
    (251, 'Fernanda Caseño Trindade Arioli', 'FEEC'),
    (252, 'José Antenor Pomilio', 'FEEC'),
    (253, 'José Pissolato Filho', 'FEEC'),
    (254, 'Luiz Carlos Pereira Da Silva', 'FEEC'),
    (255, 'Madson Cortes de Almeida', 'FEEC'),
    (256, 'Marconi Kolm Madrid', 'FEEC'),
    (257, 'Marcos Julio Rider Flores', 'FEEC'),
    (258, 'Maria Cristina Dias Tavares', 'FEEC'),
    (259, 'Pedro Luis Dias Peres', 'FEEC'),
    (260, 'Ricardo Coração de Leão de Oliveira', 'FEEC'),
    (261, 'Secundino Soares Filho', 'FEEC'),
    (262, 'Takaaki Ohishi', 'FEEC'),
    (263, 'Tárcio André dos Santos Barros', 'FEEC'),
    (264, 'Walmir de Freitas Filho', 'FEEC');




